# Generated by Django 5.0.1 on 2024-01-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("danalysis", "0002_alter_organisation_id_alter_sector_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InlineQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InlineQuestionFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.CharField(blank=True, max_length=255)),
                ("createdAt", models.DateTimeField(blank=True)),
                ("updatedAt", models.DateTimeField(blank=True)),
                (
                    "deviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="danalysis.device",
                    ),
                ),
                (
                    "inlineQuestionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_question_feedback",
                        to="questions.inlinequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "chapterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_chapter",
                        to="questions.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("feedback", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(blank=True)),
                ("updatedAt", models.DateTimeField(blank=True)),
                (
                    "deviceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="danalysis.device",
                    ),
                ),
                (
                    "questionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_feedback",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
