# Generated by Django 5.0.1 on 2024-01-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("appversion", models.CharField(blank=True, max_length=255)),
                ("deviceModel", models.CharField(blank=True, max_length=255)),
                ("os", models.CharField(blank=True, max_length=255)),
                ("osversion", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("route", models.CharField(max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("destinationState", models.CharField(blank=True, max_length=255)),
                (
                    "deviceId",
                    models.ForeignKey(
                        blank=True,
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="danalysis.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sectorId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="danalysis.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.AutoField(max_length=255, primary_key=True, serialize=False),
                ),
                ("age", models.CharField(blank=True, max_length=255)),
                ("gender", models.CharField(blank=True, max_length=255)),
                ("locale", models.CharField(blank=True, max_length=255)),
                ("createdAt", models.DateTimeField(blank=True)),
                ("updatedAt", models.DateTimeField(blank=True)),
                (
                    "deviceId",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers_device",
                        to="danalysis.device",
                    ),
                ),
                (
                    "organisationId",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers_organisation",
                        to="danalysis.organisation",
                    ),
                ),
                (
                    "routeId",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers_route",
                        to="danalysis.route",
                    ),
                ),
                (
                    "sectorId",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers_sector",
                        to="danalysis.device",
                    ),
                ),
            ],
        ),
    ]
