# Generated by Django 5.0.1 on 2024-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("danalysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sector",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="worker",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
