# Generated by Django 5.0.1 on 2024-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("danalysis", "0003_alter_device_osversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="appversion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="deviceModel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="os",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="osversion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
