# Generated by Django 5.0.1 on 2024-01-13 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("danalysis", "0004_alter_device_appversion_alter_device_devicemodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="deviceId",
        ),
    ]
