# Generated by Django 5.0.1 on 2024-01-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("danalysis", "0005_remove_route_deviceid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="sectorId",
        ),
        migrations.AddField(
            model_name="organisation",
            name="sectors",
            field=models.ManyToManyField(to="danalysis.sector"),
        ),
    ]
